# Generated by Django 5.0 on 2023-12-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('opinion', models.TextField(max_length=1000)),
                ('console', models.CharField(choices=[('Xbox', 'Xbox'), ('PC', 'PC'), ('Nintendo Switch', 'Nintendo Switch'), ('PS5', 'PS5'), ('Sin Información', 'Sin Información')], max_length=20)),
                ('release_date', models.DateField()),
                ('category', models.CharField(choices=[('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Familiar', 'Familiar'), ('Deporte', 'Deporte'), ('Terror', 'Terror')], max_length=20)),
            ],
        ),
    ]
