# Generated by Django 5.0 on 2023-12-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondGames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='front_page',
            field=models.ImageField(default='/no_disponible.png', upload_to='BeyondGames/images/'),
        ),
    ]
