# Generated by Django 5.0 on 2023-12-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondGames', '0003_publicacion_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='front_page',
            field=models.ImageField(default='/media/BeyondGames/images//no_disponible.png', upload_to='BeyondGames/images/'),
        ),
    ]
