# Generated by Django 5.0 on 2023-12-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondGames', '0004_alter_publicacion_front_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='front_page',
            field=models.ImageField(default='media/BeyondGames/images/no_disponible.png', upload_to='BeyondGames/images/'),
        ),
    ]
